### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by derciopale** [Samuel-Bie/mpesa-laravel-sdk#1]
require(C:\xampp\htdocs\daw\dawsemestral\vendor\samuelbie\mpesa\src/config/mpesa.php): failed to open stream: No such file or directory

**Comment by Samuel-Bie** [comment]
Descreva o que aconteceu antes disso.

**Comment by derciopale** [comment]
Quando executo o comando de instalacao do pacote composer require samuelbie/mpesa
Assim como adicionando a dependencias(composer.json):



"samuelbie/mpesa": "^1.3",

composer update

Me retorna esse erro:
require(C:\xampp\htdocs\daw\dawsemestral\vendor\samuelbie\mpesa\src/config/mpesa.php): failed to open stream: No such file or directory

Laravel 8

**Comment by Samuel-Bie** [comment]
OK. Realmente havia um Bug na publicação das configurações. Ja atualizei para que possa encontrar o diretorio certo. 

Testei em Laravel 8 Funcionou perfeitamente.

Espero ter ajudado.

**Comment by derciopale** [comment]
Funcionou, Obrigado!
