### ISSUE TITLE
"Interface 'samuelbie\\mpesa\\interfaces\\TransactionInterface' not found"

### ISSUE THREAD

**Issue by eunicevassoa** [Samuel-Bie/mpesa-laravel-sdk#2]
Fiz a instalação do pacote no Laravel 8.x e ao tentar fazer uma transação de cliente para empresa tenho o seguinte erro: "Interface 'samuelbie\\mpesa\\interfaces\\TransactionInterface' not found"

![Screenshot from 2021-06-03 09-13-15](https://user-images.githubusercontent.com/45620682/120603630-87cf4b00-c44c-11eb-92b1-b60efbeddcb3.png)

**Comment by Samuel-Bie** [comment]
Ola @eunicevassoa . Olha estou mesmo esta semana a trabalhar nesse pacote. Natauralmente ja avistei alguns erros, vou verificar isso.

Abraços.

**Comment by eunicevassoa** [comment]
Está certo. Vou aguardar as correcções.

**Comment by Samuel-Bie** [comment]
@eunicevassoa qual a versao que tens Instalada??? Tens a Versao 1.4.2????

**Comment by eunicevassoa** [comment]
A versão que tenho é a 1.4
![Screenshot from 2021-06-17 10-23-06](https://user-images.githubusercontent.com/45620682/122359729-161bf480-cf56-11eb-9380-d40dcc625cb0.png)

**Comment by Samuel-Bie** [comment]
Ola @eunicevassoa bug currugido no commit [aqui](https://github.com/Samuel-Bie/mpesa-laravel-sdk/commit/4760b0e2cb753e009bdc585048311844258c1a0f).

Eu construi o pacote no windows a alguns erros de namespacing no windows sao permitidos o mesmo nao acontece no linux.

Mas Ja esta currugido.

Remova todo pacote e instale a versao 1.5.1
