### ISSUE TITLE
Fatal error: Uncaught ReflectionException: Class config does not exist

### ISSUE THREAD

**Issue by maxgilcosta** [Samuel-Bie/mpesa-laravel-sdk#3]
Em primeiro lugar, parabéns pela iniciativa. Ao tentar fazer uma conexão csb, me devolve o erro

Fatal error: Uncaught ReflectionException: Class config does not exist in /var/www/html/mpesa/vendor/laravel/framework/src/Illuminate/Container/Container.php:809 Stack trace: #0 /var/www/html/mpesa/vendor/laravel/framework/src/Illuminate/Container/Container.php(809): ReflectionClass->__construct('config') #1 /var/www/html/mpesa/vendor/laravel/framework/src/Illuminate/Container/Container.php(691): Illuminate\Container\Container->build('config') #2 /var/www/html/mpesa/vendor/laravel/framework/src/Illuminate/Container/Container.php(637): Illuminate\Container\Container->resolve('config', Array) #3 /var/www/html/mpesa/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(119): Illuminate\Container\Container->make('config', Array) #4 /var/www/html/mpesa/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(275): app('config') #5 /var/www/html/mpesa/vendor/samuelbie/mpesa/src/Config.php(73): config('mpesa') #6 /var/www/html/mpesa/vendor/samuelbie/mpesa/src/Transaction.php(48): Samuelbie\Mpesa\Config->__construc in /var/www/html/mpesa/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 811
Obrigado!

**Comment by Samuel-Bie** [comment]
@maxgilcosta Desculpas pela imensa demora, fix uns bug fixes nesta semana, e testei acho que o erro esta resolvido.

Podes por favor me dar um feed back assim que testares.

E para alem disso deves executar o comando para publicares as configurações.
